{"relationshipsSections":[{"identifiers":["doc:\/\/FoundationExtras\/SQ","doc:\/\/FoundationExtras\/s5ErrorP","doc:\/\/FoundationExtras\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/conversionFailure(message:)"]},{"identifiers":["doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Equatable-Implementations","doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Error-Implementations"],"title":"Default Implementations","generated":true}],"sections":[],"metadata":{"role":"symbol","title":"TryFrom.Failure","symbolKind":"enum","externalID":"s:16FoundationExtras7TryFromV7FailureO","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"Failure"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}],"modules":[{"name":"FoundationExtras"}]},"hierarchy":{"paths":[["doc:\/\/FoundationExtras\/documentation\/FoundationExtras","doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom"]]},"abstract":[{"type":"text","text":"A universal error type that is available to all custom implementations of the TryFrom trait."}],"identifier":{"url":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/foundationextras\/tryfrom\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}]}]}],"references":{"doc://FoundationExtras/documentation/FoundationExtras/TryFrom":{"role":"symbol","title":"TryFrom","abstract":[{"text":"Protocols in Swift are limited, period. Protocols cannot be implemented multiple times with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"different implementations!"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TryFrom","kind":"identifier"}],"type":"topic","url":"\/documentation\/foundationextras\/tryfrom","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TryFrom"}],"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom"},"doc://FoundationExtras/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/FoundationExtras\/s8SendableP","type":"unresolvable"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Equatable-Implementations","abstract":[],"kind":"article","url":"\/documentation\/foundationextras\/tryfrom\/failure\/equatable-implementations","type":"topic","role":"collectionGroup"},"doc://FoundationExtras/documentation/FoundationExtras":{"role":"collection","title":"FoundationExtras","abstract":[{"type":"text","text":"Useful extensions to the Foundation framework."}],"type":"topic","url":"\/documentation\/foundationextras","kind":"symbol","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras"},"doc://FoundationExtras/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/FoundationExtras\/s5ErrorP","type":"unresolvable"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/conversionFailure(message:)":{"title":"TryFrom.Failure.conversionFailure(message:)","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/conversionFailure(message:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversionFailure"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/foundationextras\/tryfrom\/failure\/conversionfailure(message:)","type":"topic","role":"symbol"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/Error-Implementations":{"title":"Error Implementations","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Error-Implementations","abstract":[],"kind":"article","url":"\/documentation\/foundationextras\/tryfrom\/failure\/error-implementations","type":"topic","role":"collectionGroup"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure":{"role":"symbol","title":"TryFrom.Failure","abstract":[{"text":"A universal error type that is available to all custom implementations of the TryFrom trait.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}],"type":"topic","url":"\/documentation\/foundationextras\/tryfrom\/failure","kind":"symbol","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure"},"doc://FoundationExtras/SQ":{"identifier":"doc:\/\/FoundationExtras\/SQ","title":"Swift.Equatable","type":"unresolvable"}}}